### ISSUE TITLE
Change `go` base image in `Dockerfile`

### ISSUE THREAD

**Issue by mathieu-benoit** [sigstore/cosign-gatekeeper-provider#27]
As per the discussion in there: https://github.com/sigstore/cosign-gatekeeper-provider/pull/24#pullrequestreview-1284605329.

Instead of using `go:1.20` as the base image in the `Dockerfile`, the proposal is to use `cgr.dev/chainguard/go`.

If there is an agreement with that, let's have a dedicated PR opened for that.

Additionally, some questions top of mind with that:
1. Why [`rekor`](https://github.com/sigstore/rekor/blob/main/Dockerfile#L16) or [`fulcio`](https://github.com/sigstore/fulcio/blob/main/Dockerfile#L16) are using `golang:1.20` and not
2. Based on 1., do we want to have this current project not doing like the other projects?
3. In the `Dockerfile`, the base image is in an `ARG`, which will prevent `dependabot` (#21) to update any update of this base image, do we also want to change that?
4. In the other projects, `sha` is used for the `go:1.20` image, not here, should we do that here too?

**Comment by Dentrax** [comment]
Hey @cpanato 👋 Do you have any ideas on this?

> Why [rekor](https://github.com/sigstore/rekor/blob/main/Dockerfile?rgh-link-date=2023-02-09T12%3A37%3A14Z#L16) or [fulcio](https://github.com/sigstore/fulcio/blob/main/Dockerfile?rgh-link-date=2023-02-09T12%3A37%3A14Z#L16) are using golang:1.20 and not `cgr.dev/chainguard/go`? Are there any tracking issue or plan for this?

**Comment by cpanato** [comment]
I can take a look on that and propose a PR
