### ISSUE TITLE
What's the status on the project?

### ISSUE THREAD

**Issue by ChaosInTheCRD** [sigstore/cosign-gatekeeper-provider#5]
**Question**

Hi there! This project looks awesome, but I am wondering what the short to midterm roadmap on it is. I see it is marked as not production ready. Are there any production ready projects that could help us check image signatures on admission with gatekeeper at this point?

What would you say are the main barriers to this project becoming ready for production. I noticed also that it currently can only verify images signed and logged on Reko; is there scope for adding PRs to also support regular private / public key signed images?

We are interested in the prospect of helping out here, so we can agree on some areas for us contribute 😄

**Comment by sozercan** [comment]
GK v3.11.0 graduates external data to beta: https://github.com/open-policy-agent/gatekeeper/releases/tag/v3.11.0 @dlorenc @developer-guy

**Comment by mathieu-benoit** [comment]
Hi there! 👋

@dlorenc @developer-guy, now that Gatekeeper v3.11.0 has graduated external data to beta, what's the plan to update this project/component? I also see some issues around public key as secret support, etc. any plan to support these too?

Thanks!

**Comment by dlorenc** [comment]
I'm not sure if anyone is actively working on this project now. PRs are probably welcome and I'm sure we could find a way to add more maintainers if there's enough interest!

**Comment by salaxander** [comment]
@dlorenc I think I could potentially help find some maintainers if you're open to it! I think we'd love to contribute from the Gatekeeper side

**Comment by cpanato** [comment]
we did a few ci and release improvements and need to revisit the code functionality but i think we are moving forward.
will close this issue
